spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/sandbox
    username: ${JDBC_USER}
    password: ${JDBC_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: MatorinFedorAndreevichBIB101200000
  expiration: 3600000

server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:server.jks
    key-store-type: JKS
    key-store-password: serverPass
    key-alias: server